### ISSUE TITLE
Can you change the default transform property before rendering a chart?

### ISSUE THREAD

**Issue by kcaj21** [sodaviz/soda#101]
Hi, I've been trying to work out how to make a chart be more zoomed-in on render, as some of the sequences I have are very small along a very long genome.

So far, I have succeeded in changing the transform property, but it wont be applied until a user begins to zoom - at this point it jumps very suddenly to the applied transform level. 

```
      featureViewerRef.current.transform = new Transform(2, 0, 0);
      featureViewerRef.current.render({ annotations });
```

I'm struggling to figure out how to apply the new transform value before the chart is rendered.

Do you have any advice? It would be greatly appreciated.
Thank you!

**Comment by jackroddy** [comment]
You'll want some combination of setting a `domainConstraint` and/or `zoomConstraint` on the `ChartConfig`, then providing some `start` and `end` values on the `RenderParams`.

Here's a simple [example on codepen](https://codepen.io/jackroddy/pen/rNEoabR?editors=0011), and here's the example code:
```
let chart = new soda.Chart({
  selector: "div#soda-chart",
  zoomable: true,
  resizable: true,
  // constrains panning and zooming; it's a callback
  domainConstraint: () => [0, 100_000],
  // constrains only zooming
  zoomConstraint: [0.0, Infinity],
});

fetch("https://sodaviz.org/data/examples/default")
  .then((response) => response.json())
  .then((annotations) =>
    chart.render({
      annotations,
      // set the initial domain
      start: 25_000,
      end: 30_000
    })
  );
```

Hope that helps!

**Comment by kcaj21** [comment]
This works very well, it's a massive help, thank you!

**Comment by kcaj21** [comment]
This works very well, it's a massive help, thank you!
